In [6]:
import numpy as np

student_metrics = np.random.rand(100, 3)

student_metrics[:, 0] *= 100

composite_score = (
    0.4 * student_metrics[:, 0] +
    0.4 * student_metrics[:, 1] +
    0.2 * student_metrics[:, 2]
)

print("Student Metrics Matrix:")
print(student_metrics)

print("\nComposite Scores:")
print(composite_score)

Student Metrics Matrix:
[[3.53435146e+01 7.40708227e-01 4.66552728e-01]
 [6.61874322e+01 2.68844480e-01 1.32451117e-01]
 [2.83346522e+01 2.78843085e-01 2.09032544e-02]
 [4.21703112e+01 5.01277979e-01 6.30144091e-01]
 [5.37425638e+01 5.84455959e-01 3.65512401e-01]
 [8.53450763e+00 2.65400482e-01 1.79078635e-01]
 [1.33397452e+01 7.46840703e-01 9.85027038e-01]
 [3.52205785e+00 6.57787906e-01 3.70654012e-01]
 [7.87616347e+01 7.87410511e-01 2.89619228e-01]
 [1.11145905e+01 9.39449722e-02 4.75341046e-01]
 [3.50675972e+01 8.34830249e-01 7.72724171e-01]
 [8.91257592e+01 9.80268795e-01 4.98888010e-01]
 [6.91408503e+01 3.50347501e-01 7.06163492e-01]
 [4.29191789e+01 3.63771004e-01 3.23554906e-01]
 [1.46116958e+01 7.64152436e-01 8.42429644e-01]
 [7.81035937e+01 2.07612980e-01 8.40925592e-02]
 [6.17696440e+00 1.14910092e-01 2.11822197e-01]
 [4.22416138e+01 6.78242993e-02 2.66987437e-01]
 [9.00792473e+01 1.08872465e-01 2.26753207e-01]
 [8.67555244e+01 8.64311101e-01 8.79815605e-02]
 [6.63817853e+01

In [9]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 101, 105],
    "Midterm_Score": [85.0, np.nan, 72.0, 85.0, 45.0],
    "Study_Hours": [12.0, 6.0, np.nan, 12.0, 3.0],
    "City": ["Delhi", "Mumbai", "Delhi", "Delhi", "Chennai"],
    "Passed": ["Yes", "No", "Yes", "Yes", "No"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = df.drop_duplicates()

numeric_cols = ["Midterm_Score", "Study_Hours"]

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

df = pd.get_dummies(df, columns=["City"])

print("\nProcessed DataFrame:")
print(df)

X = df.drop("Passed", axis=1)
y = df["Passed"]

print("\nFeature Matrix (X):")
print(X)

print("\nTarget Vector (y):")
print(y)


# Question - 11
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

Original DataFrame:
   Student_ID  Midterm_Score  Study_Hours     City Passed
0         101           85.0         12.0    Delhi    Yes
1         102            NaN          6.0   Mumbai     No
2         103           72.0          NaN    Delhi    Yes
3         101           85.0         12.0    Delhi    Yes
4         105           45.0          3.0  Chennai     No

Processed DataFrame:
   Student_ID  Midterm_Score  Study_Hours Passed  City_Chennai  City_Delhi  \
0         101      85.000000         12.0    Yes         False        True   
1         102      67.333333          6.0     No         False       False   
2         103      72.000000          7.0    Yes         False        True   
4         105      45.000000          3.0     No          True       False   

   City_Mumbai  
0        False  
1         True  
2        False  
4        False  

Feature Matrix (X):
   Student_ID  Midterm_Score  Study_Hours  City_Chennai  City_Delhi  \
0         101      85.000000         12.0 